pogodynkaApp/src/Entity/Measurement.php
<?php

namespace App\Entity;

use App\Repository\MeasurementRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=MeasurementRepository::class)
 */
class Measurement
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=Location::class)
     * @ORM\JoinColumn(nullable=false)
     */
    private $city_id;

    /**
     * @ORM\Column(type="date")
     */
    private $date;

    /**
     * @ORM\Column(type="decimal", precision=3, scale=0)
     */
    private $temperature;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $long_text;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $image_url;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCityId(): ?Location
    {
        return $this->city_id;
    }

    public function setCityId(?Location $city_id): self
    {
        $this->city_id = $city_id;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getTemperature(): ?string
    {
        return $this->temperature;
    }

    public function setTemperature(string $temperature): self
    {
        $this->temperature = $temperature;

        return $this;
    }

    public function getLongText(): ?string
    {
        return $this->long_text;
    }

    public function setLongText(string $long_text): self
    {
        $this->long_text = $long_text;

        return $this;
    }

    public function getImageUrl(): ?string
    {
        return $this->image_url;
    }

    public function setImageUrl(?string $image_url): self
    {
        $this->image_url = $image_url;

        return $this;
    }
}

pogodynkaApp/src/Controller/WeatherController.php
<?php // src/Controller/WeatherController.php
namespace App\Controller;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\Location;
use App\Service\WeatherUtil;
use App\Repository\MeasurementRepository;
use App\Repository\LocationRepository;

class WeatherController extends AbstractController
{
    public function cityAction($country,$city, WeatherUtil $forecast): Response
    {

    $measuerements = $forecast->getWeatherForCountryAndCity($country, $city);

    return $this->render('weather/city.html.twig', [
        'city' => $city,
        'measurements' => $measuerements,
    ]);
    }
}

pogodynkaApp/templates/weather/city.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello WeatherController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Measurement index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Date</th>
                <th>Temperature</th>
                <th>Long_text</th>
                <th>Image_url</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for measurement in measurements %}
            <tr>
                <td>{{ measurement.id }}</td>
                <td>{{ measurement.date ? measurement.date|date('Y-m-d') : '' }}</td>
                <td>{{ measurement.temperature }}</td>
                <td>{{ measurement.longText }}</td>
                <td>{{ measurement.imageUrl }}</td>
                <td>
                    <a href="{{ path('measurement_show', {'id': measurement.id}) }}">show</a>
                    <a href="{{ path('measurement_edit', {'id': measurement.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('measurement_new') }}">Create new</a>
</div>
{% endblock %} 